version: "3.9"
services:
  app:
    build:
      context: .
      target: dev
    image: kevin-adoboe/url-shortener:dev
    environment:
      - PORT=3000
      - BASE_URL=http://localhost:3000
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

